version: "3.8"
volumes:
  db-store:
  php-fpm-socket:
services:
  app:
    build: ./docker/php
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ../backend:/work/backend

  web:
    # 設計図
    build: ./docker/nginx
    # 部屋番号みたいなもの
    ports:
      # 自分のpcの80に入れば、80コンテナに入れる
      - 80:80
    
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ../backend:/work/backend

  db:
    build: ./docker/mysql
    volumes:
      - db-store:/var/lib/mysql
    ports:
      - 3308:3306
